version: '3'
services:
  estudando_spark:
    image: spark1n-image
    container_name: estudando_spark
    hostname: spark-driver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4040:4040
      - 4041:4041
      - 18080:18080
    volumes:
      - ./app:/home/sam/app
